version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7
    container_name: taskflow-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: taskmanager
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - taskflow-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: taskflow-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - taskflow-network

  # Backend API
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: taskflow-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/taskmanager?authSource=admin
      REDIS_URL: redis://redis:6379
      CLIENT_URL: http://localhost:3000
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production
      EMAIL_USER: geekhirusha@gmail.com
      EMAIL_PASS: conkfhleceskmgwc
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - redis
    networks:
      - taskflow-network

  # Frontend (Nginx)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: taskflow-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - taskflow-network

volumes:
  mongodb_data:
  redis_data:

networks:
  taskflow-network:
    driver: bridge