version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:5.0
    container_name: taskvision-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: taskvision
    volumes:
      - mongodb_data:/data/db
    networks:
      - taskvision-network

  # Redis service for session management and caching
  redis:
    image: redis:7-alpine
    container_name: taskvision-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - taskvision-network

  # TaskVision application
  app:
    build: .
    container_name: taskvision-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/taskvision?authSource=admin
      JWT_SECRET: your_super_secure_jwt_secret_for_production
      JWT_EXPIRES_IN: 7d
      CLIENT_URL: http://localhost:3000
    depends_on:
      - mongodb
      - redis
    networks:
      - taskvision-network
    volumes:
      - ./uploads:/app/server/uploads

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: taskvision-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./client/build:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - taskvision-network

volumes:
  mongodb_data:

networks:
  taskvision-network:
    driver: bridge
